import { 
  Home, ArrowUp, Settings, Database, FileEdit, Search, Link2, Calculator,
  Zap, BarChart3, Calendar, Package, BarChart, BookOpen, Target, Eye,
  Rocket, Code, AlertTriangle, Map, Building2, CheckCircle2, Dices,
  Hash, Globe, Lock, Monitor, Key, Ruler, FolderOpen, MessageSquare,
  Plus, RotateCw, Trash2, ShieldCheck, Download, FileText, Filter,
  Users, Medal, TrendingUp, Clock, Lightbulb, Trophy, Scissors,
  Shuffle, Divide, Ban, TestTube, DollarSign, GitMerge, TreeDeciduous,
  Bug, PackageOpen, CheckCheck, Percent, RefreshCw, Folder,
  Brain, GraduationCap, Briefcase, TrendingDown, Activity, Award,
  Layers, GitBranch, PieChart, LineChart, Network, Box, Cpu,
  CloudDownload, Server, Workflow, FileSpreadsheet, Grid, Layout,
  Megaphone, ShoppingCart, Heart, Coffee, Plane, Utensils,
  Stethoscope, Truck, Factory, Gamepad2, CreditCard, Film,
  BookMarked, BarChart4, Target as TargetIcon, Flag, Pin, Bell,
  Edit3, Pen, Ruler as RulerIcon, Calculator as CalculatorIcon,
  Microscope, Dna, Puzzle, Crosshair, Rainbow, Sparkles, Palette,
  Drama, Image, Paperclip, Link, Repeat, Repeat1, Repeat2, Bot,
  Smartphone, Wrench, PartyPopper, HardDrive, Star, Gift,
  Flame, Pencil, LucideProps
} from "lucide-react";

// 完整的 emoji 到 Lucide 图标映射
export const emojiIconMap: { [key: string]: React.ComponentType<LucideProps> } = {
  // 基础图标
  '🔢': Hash,
  '🌐': Globe,
  '⚙️': Settings,
  '🔐': Lock,
  '🖥️': Monitor,
  '📊': BarChart3,
  '🔑': Key,
  '📐': Ruler,
  '🗂️': FolderOpen,
  '💬': MessageSquare,
  '➕': Plus,
  '🔄': RotateCw,
  '🗑️': Trash2,
  '🔒': ShieldCheck,
  '📥': Download,
  '🔍': Search,
  '🎯': Target,
  '📄': FileText,
  '🔗': Link2,
  '⚡': Zap,
  '🚫': Ban,
  '✂️': Scissors,
  '📅': Calendar,
  '🎲': Dices,
  '🔀': Shuffle,
  '🚀': Rocket,
  '💡': Lightbulb,
  '🏆': Trophy,
  '🥇': Medal,
  '📈': TrendingUp,
  '⏰': Clock,
  '👥': Users,
  '🐍': Code,
  '📚': BookOpen,
  '🧪': TestTube,
  '💰': DollarSign,
  '🌲': TreeDeciduous,
  '🐌': Bug,
  '🔌': Zap,
  '🛡️': ShieldCheck,
  '🐼': Package,
  '⚠️': AlertTriangle,
  '🗺️': Map,
  '🏢': Building2,
  '✅': CheckCircle2,
  '👤': Users,
  '🧠': Brain,
  '🎓': GraduationCap,
  '💼': Briefcase,
  '📉': TrendingDown,
  '🏅': Award,
  '🎖️': Medal,
  '📂': Folder,
  '☁️': CloudDownload,
  '📋': FileSpreadsheet,
  '🎨': Layout,
  '📣': Megaphone,
  '🛒': ShoppingCart,
  '❤️': Heart,
  '☕': Coffee,
  '✈️': Plane,
  '🍽️': Utensils,
  '🏥': Stethoscope,
  '🚚': Truck,
  '🏭': Factory,
  '🎮': Gamepad2,
  '💳': CreditCard,
  '🎬': Film,
  '📖': BookMarked,
  '💻': Monitor,
  '🌳': TreeDeciduous,
  '💾': HardDrive,
  '🌟': Star,
  '🎁': Gift,
  '✨': Sparkles,
  '🔥': Flame,
  '💪': Activity,
  '🚩': Flag,
  '📌': Pin,
  '🔔': Bell,
  '📝': Edit3,
  '🖊️': Pen,
  '✏️': Pencil,
  '📏': RulerIcon,
  '🧮': CalculatorIcon,
  '🔬': Microscope,
  '🧬': Dna,
  '🧩': Puzzle,
  '🏹': Crosshair,
  '🎪': PartyPopper,
  '🌈': Rainbow,
  '🔮': Eye,
  '🎭': Drama,
  '🖼️': Image,
  '🖇️': Paperclip,
  '📎': Paperclip,
  '⛓️': Link,
  '🔁': Repeat,
  '🔂': Repeat1,
  '🔃': Repeat2,
  '📱': Smartphone,
  '🔧': Wrench,
};

// 主要导出函数
export const getLucideIcon = (
  emojiName: string, 
  className?: string,
  strokeWidth: number = 1,
  absoluteStrokeWidth: boolean = true
) => {
  const IconComponent = emojiIconMap[emojiName] || BarChart3;
  return (
    <IconComponent 
      className={className || 'w-5 h-5'} 
      strokeWidth={strokeWidth} 
      absoluteStrokeWidth={absoluteStrokeWidth}
    />
  );
};

export default getLucideIcon;
